
"""
    DataType 使用的字符串
"""
class DataString:
    TYPE_SENSOR = "SENSOR"
    TYPE_AUDIO = "AUDIO"
    TYPE_PICTURE = "PICTURE"
    TYPE_VIDEO = "VIDEO"
    TYPE_ACCELEROMETER = "ACCELEROMETER"
    TYPE_GYROSCOPE = "GYROSCOPE"
    TYPE_ROTATION_VECTOR = "ROTATION_VECTOR"
    TYPE_MAGNETIC_FIELD = "MAGNETIC_FIELD"
    TYPE_LIGHT = "LIGHT"
    TYPE_PRESSURE = "PRESSURE"
    TYPE_GRAVITY = "GRAVITY"
    TYPE_LINEAR_ACCELERATION = "LINEAR_ACCELERATION"
    TYPE_MAGNETIC_FIELD_UNCALIBRATED = "MAGNETIC_FIELD_UNCALIBRATED"
    TYPE_GAME_ROTATION_VECTOR = "GAME_ROTATION_VECTOR"
    TYPE_GYROSCOPE_UNCALIBRATED = "GYROSCOPE_UNCALIBRATED"
    TYPE_LOW_LATENCY_OFFBODY_DETECT = "LOW_LATENCY_OFFBODY_DETECT"
    TYPE_PROXIMITY = "PROXIMITY"
    TYPE_RELATIVE_HUMIDITY = "RELATIVE_HUMIDITY"
    TYPE_AMBIENT_TEMPERATURE = "AMBIENT_TEMPERATURE"
    TYPE_POSE_6DOF = "POSE_6DOF"
    TYPE_STATIONARY_DETECT = "STATIONARY_DETECT"
    TYPE_MOTION_DETECT = "MOTION_DETECT"
    TYPE_HEART_BEAT = "HEART_BEAT"
    TYPE_ACCELEROMETER_UNCALIBRATED = "ACCELEROMETER_UNCALIBRATED"

"""
    PDU 使用的字符串
"""
class PDUString:
    # 特殊值
    VALUE_HEART_BEAT = "heartbeat"

    # 复用名
    REUSE_NAME_HEART_BEAT = "HeartBeat"
    REUSE_NAME_REMOTE_SWITCH = "RemoteSwitch"

    """
        Switch 的特殊字符串
    """
    # 报文类型
    SWITCH_TYPE_CONTROL = "TYPE_CONTROL"
    SWITCH_TYPE_SYN = "TYPE_SYN"
    SWITCH_TYPE_MSG = "TYPE_MSG"

    # 控制类型
    SWITCH_CONTROL_SWITCH_ON = "CONTROL_SWITCH_ON"
    SWITCH_CONTROL_SWITCH_OFF = "CONTROL_SWITCH_OFF"