# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './SaveView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveDialog(object):
    def setupUi(self, SaveDialog):
        SaveDialog.setObjectName("SaveDialog")
        SaveDialog.resize(419, 70)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        SaveDialog.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SaveDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(SaveDialog)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.SavePushButton = QtWidgets.QPushButton(SaveDialog)
        self.SavePushButton.setObjectName("SavePushButton")
        self.horizontalLayout_2.addWidget(self.SavePushButton)
        self.CancelPushButton = QtWidgets.QPushButton(SaveDialog)
        self.CancelPushButton.setObjectName("CancelPushButton")
        self.horizontalLayout_2.addWidget(self.CancelPushButton)

        self.retranslateUi(SaveDialog)
        QtCore.QMetaObject.connectSlotsByName(SaveDialog)

    def retranslateUi(self, SaveDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveDialog.setWindowTitle(_translate("SaveDialog", "Save"))
        self.label.setText(_translate("SaveDialog", "Save Data?"))
        self.SavePushButton.setText(_translate("SaveDialog", "Save"))
        self.CancelPushButton.setText(_translate("SaveDialog", "Cancel"))
